project:
  type: website
  output-dir: docs

resources:
  - files/

website:
  title: "Mana Hariri"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Experience"
        href: experience.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Resume"
        href: resume.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/manahariri
      - icon: envelope
        href: mailto:manahariri1383@gmail.com
    background: "#CDC1C5"
    foreground: "secondary"
    border: true

format:
  html:
    css: styles.css


      

