project:
  type: website
  output-dir: docs
  resources:
  - files/**

website:
  title: "Mana Hariri"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Experience"
        href: experience.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
    right:
      - icon: linkedin
        href: www.linkedin.com/in/manahariri
    background: "#CDC1C5"
    foreground: "secondary"
    border: true
    

      



format:
  html:
    theme: 
      light: flatly
      dark: darkly
    backgroundcolor: "#FFF0F5"
    css: styles.css
    toc: false
    fontsize: 1.0em
    linestretch: 2
    page-layout: full
    smooth-scroll: true

editor: visual

