---
about:
  template: solana
---

## Work Experience

#### UCLA Lab School \| Sept 2022 - present

*Classroom Assistant*

-   Supported student groups and designed lesson activities, **applying computational tools (e.g., smart boards, 3D modeling)** to enhance learning.

-   Practiced **effective communication and problem-solving** in collaborative settings.

## Leadership & Service

#### Multi-Interest Greek Council \| Sept 2024 - present

*President*

-   **Led and directed** an executive board.

-   **Created, communicated and implemented** the organization’s vision, mission and overall direction.

-   Appointed committee chairs and **delegated tasks** as necessary.

#### Iranian Student Group \| June 2024 - present

*Cultural Director*

-   Facilitated and organized all aspects of volunteering such as recruiting new volunteers and promoting opportunities.

-   Remained well-organized and **managed schedules, tasks, and resources efficiently.**

-   Handled the diverse needs of volunteers and ensured the smooth functioning of volunteer activities.\

#### Learning Assistant Program \| September 2024 - present

*Learning Assistant*

-   Deepened an understanding of teaching as a collaborative, empathetic, and student-centered process.

-   Fostered a deeper appreciation for **collaborative interactions with Learning Assistants, instructors, and peers,** recognizing their impact on personal and professional growth.\

#### Sigma Pi Sigma Psi \| September 2022 - present

*Internal Vice President*

-   Ensured compliance with **organizational standards and regulatory requirements**.

-   Promoted a positive and inclusive organizational culture.

-   Facilitated communication and collaboration between different departments.
