---
---
Mana Hariri
---

My name is Mana Hariri, and I am a fourth-year student at the University of California, Los Angeles (UCLA) pursuing a double major in Applied Mathematics and Statistics & Data Science. In addition to my two majors, I am specializing in computing, which has allowed me to develop strong technical and programming skills. I have extensive experience working with languages such as C++, Python, and R, which I regularly use for statistical analysis, data modeling, and computational problem solving. My expected graduation date is June 2026.

### Explore the Site

::::::: grid
::: g-col-2
#### [**About**](about.qmd)
:::

::: g-col-2
#### [**Projects**](projects.qmd)
:::

::: g-col-2
#### [**Resume**](resume.qmd)
:::

::: g-col-2
#### [**Experience**](experience.qmd)
:::
:::::::

------------------------------------------------------------------------

### Skills

**Languages:** R, Python, C++\
**Tools:** Git, Quarto, LaTeX\
**Focus:** Data Science, Machine Learning, Statistical Modeling
